name: xeus-kernel
channels:
  - https://repo.prefix.dev/conda-forge
  - https://repo.prefix.dev/emscripten-forge-dev
dependencies:
  - ipython<9
  - xeus-python
  - datascience==0.18.1
  - otter-grader-base
  - numpy==2.2.6
  - scipy==1.14.1
  - urllib3<2.0
